spring:
  main:
    banner-mode: OFF
  data:
    mongodb:
      database: smoothiedb
      host: localhost
      port: 27017
server:
  port: 8085
  
management:
  endpoints.web:
    base-path: /
    path-mapping:
      health: health-check
    exposure:
      include:
        - health
  endpoint:
    health:
      probes:
        enabled: true